version: '3.1'
services:
  pg:
    build:
      dockerfile: ./Dockerfile
      context: ./postgres
    ports:
      - 5438:5432
    environment:
      POSTGRES_USER: findmyride
      POSTGRES_PASSWORD: findmyride
      POSTGRES_DB: findmyride
    command: -c 'config_file=/etc/postgresql/postgresql.conf'

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: findmyride
      MINIO_ROOT_PASSWORD: findmyride
    command: ['server', '--address', ':9000', '--console-address', ':9001', '/data']
    ports:
      - 9010:9000
      - 9011:9001

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    volumes:
      - ./minio/init.sh:/init.sh
    entrypoint: /bin/sh -c "/init.sh"
